name: world

networks:
  elwarknetwork:
    name: elwark_network
    external: true

services:
  world.api:
    image: "elwark/world/api:${TAG:-latest}"
    container_name: "world_api"
    build:
      context: .
      dockerfile: src/World.Api/Dockerfile
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Serilog__WriteTo__0__Name=Console
      - "Serilog__WriteTo__0__Args__outputTemplate=[{Timestamp:HH:mm:ss} {Level:u3}] {TraceId} {SourceContext}: {Message}{NewLine}{Exception}"
      #      - Serilog__WriteTo__0__Args__formatter=Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact
      - Kestrel__EndPoints__Http__Url=http://+:80
      - ConnectionStrings__Postgresql=Host=postgresql;Database=world;Username=master_account;Password=master_password
      - ConnectionStrings__Redis=redis:6379,resolveDns=True,abortConnect=false,defaultDatabase=10
    ports:
      - "5006:80"
    networks:
      - elwarknetwork
