version: '3.8'

networks:
  elwarknetwork:
    name: elwark_network

services:
  world.api:
    container_name: "world_api"
    image: "elwark/world/api:${TAG:-latest}"
    build:
      context: .
      dockerfile: World.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__0__Args__formatter=Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact
      - Kestrel__EndPoints__Http__Url=http://+:80
      - Postgresql__ConnectionString=Host=postgresql;Database=world;Username=master_account;Password=master_password
    ports:
      - "5006:80"
    networks:
      - elwarknetwork
